# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base image
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire source code into the image
COPY . .

# Build the project
RUN npm run build

# Use a smaller Node.js image for the runtime
FROM node:20-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build ./build

# Copy the package.json and package-lock.json to ensure all dependencies are available
COPY package.json package-lock.json ./

# Re-install only production dependencies
RUN npm install --omit=dev

# Define environment variables
ENV NODE_ENV=production

# Define the entry point
CMD ["node", "build/index.js"]